### ISSUE TITLE
Ability to embed/create a table into a note

### ISSUE THREAD

**Issue by SaifEl-Deen** [trey-wallis/obsidian-notion-like-tables#459] opened 2023-05-22 12:06 UTC
### Problem

Ability to show/embed tables into other notes would be a nice feature, you know when you have comments/images or any other information you want to merge with the table in a single view.

### Solution

Add the ability to embed tables or directly create them within a note.

**Comment by AnnW-123** [comment] 2023-05-26 08:46
agree! looking fw to that!

**Comment by MSBack** [comment] 2023-05-30 19:02
Duplicate of #322 and #345 and #367.

This feature is up next on the [roadmap](https://github.com/users/trey-wallis/projects/2).

**Comment by trey-wallis** [comment] 2023-06-02 23:13
@MSBack  @SaifEl-Deen  @AnnW-123  @SPiCaRiA  @mvrai Added in 6.14.0.

**Closed by trey-wallis** 2023-06-02 23:13 UTC
Labels: enhancement
